image: $DOCKER_IMAGE

before_script:
  - python3 -m pip install -r requirements.txt
  - apt update && apt install -y git

variables:
  DOCS_DIR: '.'
  CONF_PY_STRING: '\nhtml_context = {"conf_py_path": "$DOCS_DIR/source/"}'

build-and-deploy:
  tags:
    - docs
  script:
    - cd $DOCS_DIR
    - echo -e $CONF_PY_STRING >> source/conf.py
    - make html
    - rm -R build/html/_sources
    - make text
    - find build/text/ -type f -name '*.txt' -execdir rename 's/\.txt/\.rst\.txt/' {} \;
    - mv build/text build/html/_sources
    - mv build/html $CI_PROJECT_NAME
    - cp -r $CI_PROJECT_NAME /opt/docs/

  artifacts:
    paths:
      - $DOCS_DIR/$CI_PROJECT_NAME
